# Generated by Django 4.1.7 on 2023-03-08 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0003_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='products',
            new_name='product',
        ),
    ]
