# Generated by Django 4.1.7 on 2023-03-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0004_rename_products_cart_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('EL', 'Electronics'), ('CL', 'Clothes'), ('FW', 'Footwears'), ('JW', 'Jewelries'), ('BG', 'Bags'), ('PH', 'Phones')], max_length=2),
        ),
    ]
