# Generated by Django 4.1.7 on 2023-05-19 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appli', '0005_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='locality',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='lastname',
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(default='none', max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserPaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acct_number', models.CharField(max_length=15)),
                ('cvv', models.PositiveIntegerField(default=0)),
                ('age', models.IntegerField(default=1)),
                ('marital_status', models.CharField(max_length=50)),
                ('card_color', models.CharField(max_length=50)),
                ('card_type', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=500)),
                ('averageincomeexp', models.DecimalField(decimal_places=2, max_digits=12)),
                ('card_expiry_date', models.CharField(max_length=500)),
                ('card_digit', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appli.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
