# Generated by Django 4.1.7 on 2023-05-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0008_rename_order_intending_order_nonfraudcasesalert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonfraudcasesalert',
            name='cart',
        ),
        migrations.AddField(
            model_name='nonfraudcasesalert',
            name='product_title',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
