# Generated by Django 4.1.7 on 2023-05-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0009_remove_nonfraudcasesalert_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpaymentinfo',
            name='card_color',
            field=models.CharField(choices=[('Gold', 'Gold'), ('White', 'White')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userpaymentinfo',
            name='card_expiry_date',
            field=models.DateField(max_length=500),
        ),
        migrations.AlterField(
            model_name='userpaymentinfo',
            name='card_type',
            field=models.CharField(choices=[('Verve', 'Verve'), ('Visa', 'Visa'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userpaymentinfo',
            name='domain',
            field=models.CharField(choices=[('International', 'International'), ('Local', 'Local')], max_length=500),
        ),
    ]
