# Generated by Django 4.1.7 on 2023-05-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0010_alter_userpaymentinfo_card_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpaymentinfo',
            name='card_expiry_date',
            field=models.DateField(),
        ),
    ]
