# Generated by Django 4.1.7 on 2023-05-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0011_alter_userpaymentinfo_card_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpaymentinfo',
            name='card_expiry_date',
            field=models.CharField(max_length=500),
        ),
    ]
